name: Dependabot auto-merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Dependabot Metadata
        run: |
          echo "Dependency Names: '${{ steps.metadata.outputs.dependency-names }}'"
          echo "Update Type: '${{ steps.metadata.outputs.update-type }}'"

      - name: Enable Auto-Merge for Dependabot PRs
        if: steps.metadata.outputs.dependency-names != ''
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --merge "$PR_URL"
