name: Auto-Merge Dependabot PRs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

    steps:
      - name: Check PR Mergeability
        id: check_merge
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            if (pullRequest.mergeable_state !== 'clean') {
              core.setFailed('PR is not ready to be merged.');
            }

      - name: Merge PR
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
