name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Author and Status
        id: check_dependabot
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" != "dependabot[bot]" ]]; then
            echo "Not a Dependabot PR. Skipping merge."
            exit 0
          fi

      - name: Auto-Merge PR
        if: github.event.pull_request.mergeable_state == 'clean'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
